---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
# Symbiote\QueuedJobs\Services\QueuedJobService\QueuedJobsService:
#   memory_limit: 8096m
HomePage:
  extensions:
    - HomePageExtension
HomePageController:
  extensions:
    - HomePageControllerExtension
SilverStripe\View\SSViewer:
  rewrite_hash_links: false
Symbiote\QueuedJobs\Jobs\CleanupJob:
  is_enabled: true
